name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*'   # 只有推送 tag 如 v1.0.0 才会触发发布

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate Changelog
        if: github.event_name == 'push'
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build and Publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run publish
